name: ServerMonitor
main: net.myunco.servermonitor.ServerMonitor
version: 1.4.2-SNAPSHOT
api-version: 1.13
author: myunco
website: https://github.com/myunco/ServerMonitor
description: This is a Bukkit plugin designed to record the operational information of a Minecraft server and save logs, review player behavior, and issue security warnings when necessary, helping server owners avoid malicious sabotage.
  For a detailed description of the plugin, please visit https://myunco.net/thread-2-1-1.html
commands:
  ServerMonitor:
    description: This is main command of the plugin.
    usage: §e/ServerMonitor §3<§ahelp§c|§areload§c|§aversion§3>
    aliases: sm
    permission: servermonitor.admin
    permission-message: "§cYou don't have permission!"
permissions:
  servermonitor.admin:
    description: Has permission to access the all ServerMonitor command
    default: op
