name: ServerMonitor
main: ml.mcos.servermonitor.ServerMonitor
version: 1.4.0
api-version: 1.13
author: unco_
website: https://www.mcbbs.net/thread-995756-1-1.html
commands:
  ServerMonitor:
    description: This is main command of the plugin.
    usage: §e/ServerMonitor §3<§ahelp§c|§areload§c|§aversion§3>
    aliases: sm
    permission: servermonitor.use
    permission-message: "§cYou don't have permission!"
permissions:
  servermonitor.use:
    description: Has permission to access the all ServerMonitor command
    default: op
