name: ServerMonitor
main: com.github.myunco.servermonitor.ServerMonitor
version: 1.1.1
author: unco_
commands:
  ServerMonitor:
    description: This is main command of the plugin.
    usage: §e/ServerMonitor §3<§ahelp§c|§areload§c|§aversion§3>
    aliases: [sm]
    permission: servermonitor.use
    permission-message: "§cYou don't have permission!"